name: Build frontend

on:
  push:
    paths:
      - "custom_components/thehague_parking/frontend/src/**"
      - ".github/workflows/frontend.yml"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: custom_components/thehague_parking/frontend
        run: npm ci

      - name: Build frontend
        working-directory: custom_components/thehague_parking/frontend
        run: npm run build

      - name: Check git status
        run: |
          git diff --exit-code
